# Render blueprint
services:
  - type: web
    name: dualasset-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: MIN_APR
        value: "0.5"
      - key: SCAN_SYMBOLS
        value: "BTC,ETH"
      - key: SCAN_DURATIONS_DAYS
        value: "2,3,4,7"
      - key: BYBIT_COOKIES_JSON
        sync: false
